# This is the config file for building CCGL with Travis-ci.org
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  global:
    - GITHUB_REPO='crazyzlj/CCGL'
    - secure: "K0C9zyvgZ02k6/CYkKGyRBeOOywgLrBjNG0Rbv3/s8BmL2ktGUYxmUvmHRnBOjO3BuEDRriblyCRHvVAhzrJILsH1FUf8Bhgizu70id1O7jaj5R26jbtGvnUa6zTu2qCa4u5eBZyhaYPww5XSSxha0qpmTmXs9pdvY0TjgmOgGPXHQXOdIppAiEr6rQEKX3p0kTfUAWZkefppXai0+MCQcIpI43iz/Jnhq65ZS3yqnq7scBkmcSUSHEqV6ym64iiASqbWv9X/L+E2v1n5OCvGO2eWz3iv+63tFBEmDJlZ+G2ZADfxg9LZDsh6owI3y+vfPQ0zRyemmIyjXgrD/W8ksVtUr+DWTPNhot6jCiwPcN1oHCyw/K41zev0LelqU7FTa6/d2SCzBYMQsiIcCVHkOi7o9ZG7mwNLmGSDFUFulIxbftWKMLZJmthwyryjmtqpsvdZxQMp81IJYjBK1qyswxieBQraSTEPHVt2Gm7LysJ7tHWJhSFdnkAtyuwJukDZlFapRMPJbeoPE33WZwotrArt8h7wJybtkgbC3mxuk4kvOaoitSqT5A/5iswRi200th4Z6XrrSAYrfoILncTVnt1TicqcVac5TfgeubE2j4wouwAyYwrdx6PbN0OAkF6hr9KhIlTeyRHovrVTR1/XKPG1YEN5vgstYGWNLQOh8A="
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.1
      language: cpp
      compiler: clang
      sudo: required
      cache:
        apt: true
        directories:
        - $HOME/.ccache
      env:
        - BUILD_NAME=osx_clang
        - DETAILS="libtool"
        - ENABLE_CXX11=1
    - os: linux
      dist: xenial
      compiler: gcc
      language: cpp
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      addons:
        apt:
          packages:
            - lcov
            - doxygen
      services:
        - mongodb
      env:
        - BUILD_NAME=linux_gcc
        - ENABLE_CXX11=1
        - RUN_TESTS=true
        - COVERAGE=false
before_install:
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/before_install.sh
  - ./doc/ci/travis/${BUILD_NAME}/before_install.sh
install:
  - chmod +x ./doc/travis-doxygen.sh
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/install.sh
  - ./doc/ci/travis/${BUILD_NAME}/install.sh
script:
  - chmod +x ./doc/ci/travis/${BUILD_NAME}/script.sh
  - ./doc/ci/travis/${BUILD_NAME}/script.sh

notifications:
  email:false
